var navs = [
    {
        "title":"产品管理",
        "icon":"fa-cubes",
        "href":"goods/goodslist.html"
    },{
        "title":"订单管理",
        "icon":"fa-cubes",
        "href":"orderlist.html"
    },{
        "title":"代理商",
        "icon":"fa-cubes",
        "href":"agents/agents.html"
    },{
        "title":"商户",
        "icon":"fa-cubes",
        "href":"commercia/commercia.html"
    },{
        "title":"财务管理",
        "icon":"fa-cubes",
        "children":[
            {
                "title":"概览",
                "icon":"&#xe60a",
                "href":"finance/summary.html"
            },{
                "title":"商户 ",
                "icon":"&#xe60a",
                "href":"finance/merchant.html"
            },{
                "title":"代理商 ",
                "icon":"&#xe60a",
                "href":"finance/agent.html"
            },{
                "title":"收支明细",
                "icon":"&#xe60a",
                "href":"finance/budget_details.html"
            }
        ]
    },{
        "title":"短信管理",
        "icon":"fa-cubes",
        "children":[
            {
                "title":"短信模版",
                "icon":"&#xe60a",
                "href":"sms/smstemplate.html"
            },{
                "title":"短信发送记录",
                "icon":"&#xe60a",
                "href":"sms/smsrecord.html"
            }
        ]
    },{
        "title":"系统管理",
        "icon":"fa-cubes",
        "children":[
            {
                "title":"账户管理",
                "icon":"&#xe60a",
                "href":"system/accountlist.html"
            },{
                "title":"角色权限",
                "icon":"&#xe638",
                "href":"system/role.html"
            },{
                "title":"系统参数",
                "icon":"&#xe60a",
                "href":"system/config.html"
            },{
                "title":"操作日志",
                "icon":"&#xe638",
                "href":"system/logs.html"
            }
        ]
    },
    {
        "title":"代理商(管理平台)",
        "icon":"fa-cubes",
        "children":[
            {
                "title":"申请代理商",
                "icon":"&#xe60a",
                "href":"agent/register.html"
            },
            {
                "title":"登录",
                "icon":"&#xe638",
                "href":"agent/sign.html"
            },
            {
                "title":"下属商户",
                "icon":"&#xe60a",
                "href":"agent/tenantlist.html"
            },
            {
                "title":"代理提成",
                "icon":"&#xe638",
                "href":"../activity/msgtempletindex"
            },
            {
                "title":"财务中心",
                "icon":"&#xe60a",
                "href":"../activity/activityindex"
            },
            {
                "title":"账户中心",
                "icon":"&#xe638",
                "href":"../activity/msgtempletindex"
            },
        ]
    },
    {	"title":"商户(管理平台)",
        "icon":"fa-cubes",
        "children":[
            {
                "title":"登录",
                "icon":"&#xe638",
                "href":"agent/sign.html"
            },
            {
                "title":"公众号管理",
                "icon":"&#xe60a",
                "href":"agent/tenantlist.html"
            },
            {
                "title":"我的订单",
                "icon":"&#xe638",
                "href":"merchants/orders.html"
            },
            {
                "title":"我的消费",
                "icon":"&#xe60a",
                "href":"merchants/consume.html"
            },
            {
                "title":"账户中心",
                "icon":"&#xe638",
                "href":"../activity/msgtempletindex"
            },
        ]
    }
]